### ISSUE TITLE
Request to create new branch 16, in order to migrate

### ISSUE THREAD

**Issue by DorianMAG** [shopinvader/pattern-import-export#124]
Hello, would you be ready to create a 16.0 branch. 
We would like to contribute to the migration to V16. 
Best Regards

**Comment by flotho** [comment]
Hi @sbidoul @sebastienbeau ,
we're starting to migrate this repo in v16 with @DorianMAG , any chance to have a procedure so that we could submit a PR ?
Regards

**Comment by sbidoul** [comment]
@flotho I just created the 16.0 from 14.0, marked all modules `installable=False` and updated the dotfiles from the latest OCA template.

To migrate, just add migration commits (including marking the migrated module `installable=True`).

**Comment by flotho** [comment]
Thanks @sbidoul , we'll restart from your branch.
From now, we saw specific pain points from 14 : 
*  do you recommend to adapt the same method _extract_records or to try a refactor of load method https://github.com/shopinvader/pattern-import-export/blob/14.0/pattern_import_export/models/base.py#L243 
* or do you recommend to adapt the way to restart a new savepoint https://github.com/shopinvader/pattern-import-export/blob/14.0/pattern_import_export/models/base.py#L246 
* AFAICS, this patch seems now useless in v16 : https://github.com/shopinvader/pattern-import-export/blob/14.0/pattern_import_export/models/patch.py#L14  

thanks for your support

**Comment by sbidoul** [comment]
@sbidoul actually I'm not familiar at all with this repo so I'm afraid and can't help much with your questions.
