### ISSUE TITLE
Rename Class

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/pattern-import-export#48]
@kevinkhao 

We should create a new class "pattern.config" that inherits "ir.exports" and move the code there

We should rename "patterned.import.export" in "pattern.file"

**Comment by kevinkhao** [comment]
re-fixed https://github.com/shopinvader/pattern-import-export/pull/52/commits/6df4aa958315a5dea3bd8129c3e558f8fcce739d

**Comment by kevinkhao** [comment]
fixed in https://github.com/shopinvader/pattern-import-export/pull/52

**Comment by kevinkhao** [comment]
done here https://github.com/shopinvader/pattern-import-export/pull/53
