### ISSUE TITLE
Remove wizard duplicated code

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/pattern-import-export#50]
When importing using the wizard or the automatic import we have some duplicated code
we should create an enqueue method on the pattern.file
@kevinkhao 

https://github.com/shopinvader/pattern-import-export/pull/47/files#diff-66fd7ed8df3e4ee1d305dc2a39320c394d676c6f32fc5e7f24e620ad771dbd36R14

**Comment by kevinkhao** [comment]
Fixed in https://github.com/shopinvader/pattern-import-export/pull/53
