### ISSUE TITLE
Rename status to state

### ISSUE THREAD

**Issue by sebastienbeau** [shopinvader/pattern-import-export#51]
Stick on odoo keyword
@kevinkhao

**Comment by kevinkhao** [comment]
rename status to state: https://github.com/shopinvader/pattern-import-export/pull/45/commits/3973325021b3cea9a5510f556a85bff0a5bfb542

**Comment by kevinkhao** [comment]
fix in https://github.com/shopinvader/pattern-import-export/pull/52
