### ISSUE TITLE
Manual testing and issues 29/10

### ISSUE THREAD

**Issue by kevinkhao** [shopinvader/pattern-import-export#54]
### introduced by pattern.config

Please check illustration for an example of the problem: we have two booleans, nr.1 is simple, nr.2 is calculated as inverse of the first one. Onchange is defined on product.template. Works fine on product.template, but not on product.product

![Peek 2020-10-30 15-25](https://user-images.githubusercontent.com/19902174/97716716-40eb3280-1ac4-11eb-8bc3-2c80ef2e3e31.gif)

In our case, we have delegated ir.exports in pattern.config. So onchanges that used to work for ir.exports don't work for pattern.config.

This causes problems on the onchanges here https://github.com/shopinvader/pattern-import-export/blob/2a748437d815b44a07ec3697810161e8cf4eee83/pattern_import_export/models/ir_exports_line.py#L84

The O2M field should know which export_id it is linked to, but it is not the case. The value is False, and the onchange raises.

Also affects functions that need the fields:

resource
model_id

**Comment by kevinkhao** [comment]
On 12.0:
When an Excel file is imported, error column is created but errors do not appear in each row
On O2M Exports, there is no tab/validation even if the sub-pattern has them

**Comment by sebastienbeau** [comment]
I close it as it's an old ticket on old version
