### ISSUE TITLE
Creating a pattern.config and defining a M2M export field in one go doesn't give expected result

### ISSUE THREAD

**Issue by kevinkhao** [shopinvader/pattern-import-export#58]
1. Click "Create" when in new pattern.config view
2. Choose all required options, take for example Contact as model
3. Don't click "Save" yet
4. Create a new export line "Tags/Name"
5. Click "Save"
6. Generate template file
7. Observe you get only one `"tag_ids"` column instead of the correct `tag_ids|1|name`

Issue does not occur if you click "Save" on step 3

**Comment by sebastienbeau** [comment]
Fixed here : https://github.com/shopinvader/pattern-import-export/commit/4bb18928e4d2da32cb74c1a3a24ac512230da5cd
