### ISSUE TITLE
Creating a single record using a sub-pattern on a O2M field breaks imports

### ISSUE THREAD

**Issue by kevinkhao** [shopinvader/pattern-import-export#93]
Scenario: 
You have two models, Parent, and Child

Parent has a O2M field called Children

You want to express that some Parent "Alice" has a Child named "Bob"

You import an excel file with something like: 
children_ids|1|name#key
Bob

Expected behaviour:
If Bob doesn't exist, a Child is created and linked to Alice (this works)
If Bob exists, nothing should happen ==> This crashes

Crash occurs only when two conditions are met:
* there is only one O2M record that is found by key
* there is no operation on this unique O2M record

Please check https://github.com/shopinvader/pattern-import-export/pull/92 for an example

**Comment by kevinkhao** [comment]
here https://github.com/odoo/odoo/blob/ce47d09c05e4bcc91ee4de68db3a7a471bcb4df8/odoo/addons/base/models/ir_fields.py#L486
we get an id with an int, split() expects str

**Comment by sebastienbeau** [comment]
PR https://github.com/shopinvader/pattern-import-export/pull/92 have been merged
